### ISSUE TITLE
ショートカットキーが使えない

### ISSUE THREAD

**Issue by shiori000000** [wantora/multiple-paste-and-go-button#27]
Firefox更新をした（Version 104.0）
昨日からショートカットキーが使えなくなりました。Ctrl+Shift+V
毎日使っているのでとても困っています。。ぜひ直していただきたいです。よろしくお願いいたします。

**Comment by wantora** [comment]
元のショートカットキーが使えなくなったようなので別のショートカットキー (Ctrl+Alt+V) に変更しました。
バグ報告ありがとうございました！

**Comment by shiori000000** [comment]
​Ctrl+Shift+Vで起動いたしました！
早急な改修くださいまして大変助かりました。
本当にありがとうございます！

**Comment by shiori000000** [comment]
(Ctrl+Alt+V)でしたね
