### ISSUE TITLE
Doesn't work normally on newest Firefox 104.0 64bit

### ISSUE THREAD

**Issue by JMM72** [wantora/multiple-paste-and-go-button#28]
Using Firefox 104.0 64bit under Windows 10 (all updated). Add-on version 2.6.2.

Ctrl+shift+V doesn't paste the URLs in the clipboard unless the add-ons page (about:addons) is open and it's also the active tab. Very weird.

I hope it's fixed soon, not the first time it happens. This is the add-on I use the most.

**Comment by wantora** [comment]
Ctrl+Shift+V was in conflict. So I changed the shortcut key to another key (Ctrl+Alt+V).
Thank you for your bug report!

**Comment by Gitoffthelawn** [comment]
@wantora 
What did Firefox v104 assign to Ctrl+Shift+V by default?  I didn't see anything about it in the Firefox changelog.

**Comment by JMM72** [comment]
Absolutely wonderful! Thank you for the quick fix and the whole extension, it's so really useful!
